export enum Lot {
  Ventilation = 'Ventilation',
  Terrassement_Réseaux = 'Terrassement_Réseaux',
  Serrurerie_Métallerie = 'Serrurerie_Métallerie',
  Revêtements_de_sols = 'Revêtements_de_sols',
  Plomberie = 'Plomberie',
  Plâtrerie_Cloisonnement = 'Plâtrerie_Cloisonnement',
  Phase_études = 'Phase_études',
  Phase_chantier = 'Phase_chantier',
  Peinture = 'Peinture',
  Menuiseries_intérieures_Agencement = 'Menuiseries_intérieures_Agencement',
  Menuiseries_extérieures = 'Menuiseries_extérieures',
  Maçonnerie_Gros_œuvre_Structure = 'Maçonnerie_Gros_œuvre_Structure',
  Installation_chantier_Nettoyage = 'Installation_chantier_Nettoyage',
  Façade = 'Façade',
  Études_Conception = 'Études_Conception',
  Électricité = 'Électricité',
  Démolition = 'Démolition',
  Cuisine = 'Cuisine',
  Couverture_Étanchéité_Zinguerie = 'Couverture_Étanchéité_Zinguerie',
  Chauffage_Ventilation_Climatisation = 'Chauffage_Ventilation_Climatisation',
  Aménagements_extérieurs = 'Aménagements_extérieurs',
  Carrelage_Faïence = 'Carrelage_Faïence'
}
